name: upstream
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 3" # At 08:00 on Wednesday # https://crontab.guru/#0_8_*_*_3
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"
    paths:
      - .github/workflows/upstream.yml # this file

jobs:
  user-journey:
    name: "user-journey"
    strategy:
      fail-fast: false
      matrix:
        plat: ["ubuntu", "windows", "macos"]
    runs-on: ${{matrix.plat}}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler: latest
      - run: spec/integration/user_journey_test.sh
        shell: bash
